add table component
RealDevSquad/feature-flag-service pull request #16
Opened 2022-06-25 05:37 UTC by pallabez

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-30 22:26 UTC, Neha requested changes
Rename the component from Table to FeatureFlagDashboard

The toggle of FF should move to the context provider

The Table component should be able to accept the API or any data from the outside. So, the Component in itself will be a black box for implementation but can accept the data from outside.

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/Table/Mock.js
> +export const featureFlagsMock = [
Covert all Mocks to `uppercase` and separate them with `underscore`

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/Table/Table.js
> +import { featureFlagsMock } from "./Mock";
Create a folder for the `constants`. Rename the `Mock` to the `stub` or `temp`.  Mock will be used when we will write the test cases. So, for temp dynamic/api data we will use  folder 'stub' or 'temp'

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/TableHeader/TableHeader.js
> +      <th className='p-4'>Feature Flag</th>
`th` should be dynamically generated. Create temp data and loop over that to populate the table head. 

As well as, I think this component folder should move inside the Table folder. (wyt?)

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/TableItem/TableItem.js
> +      <td className='px-4 py-2'>{featureFlag.name}</td>
`tr` should be dynamically generated. Create a temp data (`array`), loop over that and populat it.

Also, `TableItem` folder should move to the `table` component folder

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/TableItem/TableItem.js
> +  const lowerCaseNoSpaceName = (featureFlag.name).toLowerCase().replaceAll(' ', '_');
This should move to `util` or `helper`. We are doing 2 things through one `function`. This is not a good practice. Make 2 helper methods one for `lowerCase` and one for `removing spaces`. Also, the name of the function should be a verb so it should start with `convert` or `make`

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/TableItem/TableItem.js
> +        <label
Move this to separate component and this would be global component

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/Table/Table.js
> +    <div
We don't need a `div` here. The `table` is a wrapper in itself.

2022-06-30 22:26 UTC, Neha commented on ui/src/Components/Table/Table.js
> +        <thead>
There should be no `thead`. This `thead` should be coming from the `TableHeader`

2022-07-10 06:50 UTC, pallabez commented on ui/src/Components/Global/Toggle/Toggle.js
> +}
Should it be switched to `switch`? Ref - https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/switch_role

2022-07-10 06:52 UTC, pallabez commented on ui/src/Components/Dashboard/TableRow/TableRow.js
> +      </td>
This is the Configuration column of the table. Will include toggle, edit & delete button. Should I abstract it in a different component?

2022-07-10 06:57 UTC, pallabez commented on ui/src/test/Toggle.test.js
> +  })
Should this be tested? Toggle button works even without this attribute.

I think testing the css/classname to check if the toggle works is a bad idea.

2022-07-10 09:04 UTC, closed without merging