Route set up
RealDevSquad/feature-flag-service pull request #45
Opened 2022-07-13 08:39 UTC by akinsanmi60

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-07-14 12:44 UTC, pallabez commented
Thanks for the PR. Can you please mention the description of this PR & if it was tested in the browser?

2022-07-15 15:07 UTC, Neha requested changes
Please add the description and test-cases too for the PR

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
>  import Header from "./components/Header/Header";
The `header` is not getting used here. This should be removed from here.

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
> +      <Route path="/" />
What would come at `/`? As of now, I can only see blank page

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
> +      <Route path="/login" element={<Login />} />
These components are not imported hence it is not working. only blank pages are coming.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/61655/179249415-c0266a24-c6a6-40f4-8c8a-da5cc8369341.png">

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
> +      <Route path="/flag?mode=edit" element={<FlagEdit />} />
Same here, the components have not imported.

2022-07-15 15:07 UTC, Neha commented on ui/src/Components/FlagMode/FlagCreate.js
> +import React from "react";
@pallabez are we going to have separate components for edit and create?

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
> +    <Routes>
This should be moved to a separate folder name `Routes`. 

@pallabez  What would be the homepage? As we are not focusing on the Login screen as of now.

2022-07-15 15:07 UTC, Neha commented on ui/src/App.js
> +      <Route path="/flag?mode=create" element={<FlagCreate />} />
What would be the advantage here of the `mode=create`

2022-07-15 15:07 UTC, Neha commented on ui/src/Components/Login/Login.js
> +export const Login = () => {
We are not using this pattern for component creation. Please check the `button` or `header` to follow the same pattern.

2022-07-15 15:07 UTC, Neha commented on ui/src/Components/FlagMode/FlagEdit.js
> +const FlagEdit = () => {
We are not using this pattern for component creation. Please check the button or header to follow the same pattern.

2022-07-15 15:07 UTC, Neha commented on ui/src/Components/FlagMode/FlagCreate.js
> +const FlagCreate = () => {
We are not using this pattern for component creation. Please check the button or header to follow the same pattern.

2022-07-15 15:19 UTC, pallabez commented on ui/src/App.js
> +    <Routes>
Homepage would be dashboard. No?

2022-07-15 15:21 UTC, Neha commented on ui/src/App.js
> +    <Routes>
Well, as we decided the login is not the priority right now then yes `dashboard`. We need to also highlight in UI till `login` is not their `dashboard` view is of the `super user` or `non-super user`.

2022-07-15 15:22 UTC, pallabez commented on ui/src/App.js
> +      <Route path="/flag?mode=create" element={<FlagCreate />} />
The query would help us use same feature flag forum component to both edit & create as discussed before.

2022-07-15 15:23 UTC, pallabez commented on ui/src/Components/FlagMode/FlagCreate.js
> +import React from "react";
Nope. We were planning on reusing same component.

2022-07-15 23:12 UTC, Neha commented on ui/src/Components/FlagMode/FlagCreate.js
> +import React from "react";
Please remove the component and route.

2022-07-15 23:14 UTC, Neha commented
There are new requirements for the Route. 

We would be having:

Left Nav:

1. Users
2. Flags
3. Segments
4. Environment switching
5. Account settings

and then within the pages, we will have:

1. Create a flag
2. Delete a flag
3. Edit a flag

2022-08-10 08:31 UTC, Neha commented
Closing this PR as a new PR #64 is raised

2022-08-10 08:31 UTC, closed without merging